CREATE TABLE IF NOT EXISTS `user_histories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `resumen` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Resumen',
  `issuecve` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave de incidencia',
  `issueid` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'ID de la incidencia',
  `issuetype` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Tipo de Incidencia',
  `state` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Estado',
  `projectid` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Clave del proyecto',
  `nombredelproyecto` varchar(100) DEFAULT NULL COMMENT 'Nombre del proyecto',
  `proyectotype` varchar(100) DEFAULT NULL COMMENT 'Tipo de proyecto',
  `priority` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Prioridad',
  `resolucion` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Resolución',
  `assignperson` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Persona asignada',
  `informador` varchar(100) DEFAULT NULL COMMENT 'Informador',
  `createperson` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Creador',
  `createddate` datetime DEFAULT NULL COMMENT 'Creada',
  `lastmodified` datetime DEFAULT NULL COMMENT 'Actualizada',
  `lastview` datetime DEFAULT NULL COMMENT 'Vista por Última Vez',
  `finalizeddate` datetime DEFAULT NULL COMMENT 'Resuelta',
  `fixedversion` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Versiones corregidas',
  `component` json DEFAULT NULL COMMENT 'Componentes',
  `expirationdate` datetime DEFAULT NULL COMMENT 'Fecha de vencimiento',
  `etiquetas` json DEFAULT NULL COMMENT 'Etiquetas',
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'Descripción',
  `envioroments` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Entorno',
  `interestedpersons` json DEFAULT NULL COMMENT 'Interesados',
  `originalestimation` json DEFAULT NULL COMMENT 'Estimación original',
  `estimatedremainingWork` json DEFAULT NULL COMMENT 'Trabajo restante estimado',
  `jobtime` json DEFAULT NULL COMMENT 'Tiempo Trabajado',
  `issuelinkinternal` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Blocks)',
  `issuelinkoutgoing` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Blocks)',
  `issuelinkinternalcloner` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Cloners)',
  `issuelinkoutgoingcloner` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Cloners)',
  `issuelinkoutgoinduplicate` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Duplicate)',
  `issuelinkinternalissuesplit` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Issue split)',
  `issuelinkoutgoingissuesplit` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Issue split)',
  `issuelinkinternalproblem` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Problem/Incident)',
  `issuelinkoutgoingproblem` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Problem/Incident)',
  `issuelinkinternalrelates` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Relates)',
  `issuelinkoutgoingrelates` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Relates)',
  `attachments` json DEFAULT NULL COMMENT 'Adjunto',
  `dor` decimal(10,0) DEFAULT NULL COMMENT 'Campo personalizado (% DoR)',
  `ambiente` json DEFAULT NULL COMMENT 'Campo personalizado (Ambiente)',
  `assigneeqa` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Assignee QA)',
  `businessdata` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business Data)',
  `businessdatadate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Business Data Date)',
  `businessidea` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business Idea)',
  `po` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business PO)',
  `canal` json DEFAULT NULL COMMENT 'Campo personalizado (Canal)',
  `cardtype` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Card Type)',
  `carryover` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over)',
  `carryoverdetail` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Detail)',
  `carryoverdesviation` int DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Deviation)',
  `carryoverrecoverytime` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Recovery Time)',
  `causeoferrer` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Cause of error)',
  `codequality` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Code_quality)',
  `codingstartdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Coding start date)',
  PRIMARY KEY (`id`),
  KEY `userhistories_issueid_IDX` (`issueid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `user_histories2` (
  `id` int NOT NULL AUTO_INCREMENT,
  `issuecve` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave de incidencia',
  `complejidad` int DEFAULT NULL COMMENT 'Campo personalizado (Complejidad)',
  `componentsdor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Components)',
  `componentsdordate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Components Date)',
  `comprometida` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Comprometida)',
  `criteriaofacceptancedate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Criteria of Acceptance Date)',
  `criteriaofacceptance` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Criteria of acceptance)',
  `customtext` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Custom Text)',
  `definedenviroment` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Defined enviroment)',
  `desarrollointegradoparapruebasyliberación` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Desarrollo integrado para pruebas y liberación)',
  `dominio` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Domain)',
  `daysPassedqA` int DEFAULT NULL COMMENT 'Campo personalizado (Días transcurridos - QA)',
  `promisepod` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (En caso de que fue detectada una dependencia asociada, ¿El equipo "POD" a cargo cumplio con la promesa de dar solución?)',
  `documenteduserhistory` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (En relación a la sesión de refinamiento de la historia de usuario, ¿Se documentó y resolvieron preguntas asociadas a la funcionalidad?)',
  `epiclink` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Epic Link)',
  `epiclinkresumen` varchar(100) DEFAULT NULL COMMENT 'Epic Link Resumen',
  `errorexpectedbehaviordate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Error -  Expected Behavior Date)',
  `errorexpectedbehavior` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Error - Expected Behavior)',
  `errorhandling` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Error Handling)',
  `errorhandlingdate` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Error Handling Date)',
  `excepción` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Excepción)',
  `fechareadytoreview` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha Ready to review)',
  `fechacompromiso` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha compromiso)',
  `fechafinalización` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha finalización)',
  `fechaupdatecomprometida` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha update comprometida)',
  `flujo` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Flujo)',
  `functionalrequirements` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Functional Requirements)',
  `functionalrequirementsdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Functional Requirements Date)',
  `hoursindevreworks` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in Dev Reworks)',
  `hoursininprogress` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in In Progress)',
  `koursinonhold` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in on hold)',
  `iropstranstype` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (IROPs Trans Type)',
  `iniciativa` json DEFAULT NULL COMMENT 'Campo personalizado (Iniciativa)',
  `initiative` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Initiative)',
  `issuecolor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Issue color)',
  `j2Ctipoincidencia` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (J2C  Tipo Incidencia)',
  `journey` json DEFAULT NULL COMMENT 'Campo personalizado (Journey)',
  `kissrecoverytime` json DEFAULT NULL COMMENT 'Campo personalizado (KISS Recovery time)',
  `kpi` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (KPI)',
  `latechanges` int DEFAULT NULL COMMENT 'Campo personalizado (Late Changes)',
  `leadtime` int DEFAULT NULL COMMENT 'Campo personalizado (Lead Time)',
  `leadtimeforchangeshrs` int DEFAULT NULL COMMENT 'Campo personalizado (Lead Time for Changes (Hrs))',
  `limitedscope` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Limited Scope)',
  `metrics` json DEFAULT NULL COMMENT 'Campo personalizado (Metrics)',
  `metricsdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Metrics Date)',
  `microservicescontract` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Microservices Contract)',
  `microservicescontractdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Microservices Contract Date)',
  `mitigateddependency` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Mitigated dependency)',
  `mitigateddependencydate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Mitigated dependency Date)',
  `nodecasosdeprueba` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (No de casos de prueba)',
  `nonfunctionalrequirements` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Non Functional Requirements)',
  `nonfunctionalrequirementsdate` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Non Functional Requirements Date)',
  `onkoldreason` varchar(255) DEFAULT NULL COMMENT 'Campo personalizado (On Hold Reason)',
  `pod` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (POD)',
  `persistenterror` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Persistent Error)',
  `prioridadbacklog` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Prioridad Backlog)',
  `projectbenefitold` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Project Benefit - old)',
  `projectcostold` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Project Cost - old)',
  `pruebas` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Pruebas)',
  `qalead` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (QA Lead)',
  `quarter` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Quarter)',
  `ranked` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Rank)',
  `refinedcard` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Refined card)',
  `releasedeviation` int DEFAULT NULL COMMENT 'Campo personalizado (Release Deviation)',
  `releasedateactual` datetime DEFAULT NULL COMMENT 'Campo personalizado (Release date actual)',
  `releaseversion` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Release version)',
  `releasedateplanned` datetime DEFAULT NULL COMMENT 'Campo personalizado (Release date planned)',
  `reportadopor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Reportado por)',
  `resolución` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Resolución)',
  `performancetestedbefore` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Si el defecto está relacionado con el rendimiento, ¿se realizaron pruebas de rendimiento que pudieran haber identificado el defecto?)',
  `softwarefactorymember` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Software Factory Member)',
  `specialpnrgeneration` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Special PNR Generation)',
  `specialpnrgenerationdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Special PNR Generation Date)',
  `sprint` json DEFAULT NULL COMMENT 'Sprint',
  `sprintactual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint Actual)',
  `sprintappactual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Actual)',
  `sprintappplanned` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Planned)',
  `sprintenddate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint End Date)',
  `sprintplanned` varchar(10) DEFAULT NULL COMMENT 'Campo personalizado (Sprint Planned)',
  `sprintstartdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint Start Date)',
  `startdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Start date)',
  `storypointreestimation` int DEFAULT NULL COMMENT 'Campo personalizado (Story Point Reestimation)',
  `storypoints` int DEFAULT null COMMENT 'Campo personalizado (Story Points)',
  `storypointsQA` int DEFAULT null COMMENT 'Campo personalizado (Story Points QA)',
  `technicalLead` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Technical Lead)',
  `technicalsolution` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Technical Solution)',
  `technicalsolutiondetail` varchar(2048) DEFAULT NULL COMMENT 'Campo personalizado (Technical Solution Detail)',
  `testingstrategy` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Testing Strategy)',
  `testingstrategydate` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Testing Strategy Date)',
  `timeindevrework` varchar(20) DEFAULT NULL COMMENT 'Campo personalizado (Time in Dev Rework)',
  `timeininprogress` varchar(20) DEFAULT NULL COMMENT 'Campo personalizado (Time in In Progress)',
  `timeinonhold` varchar(20) DEFAULT NULL COMMENT 'Campo personalizado (Time in On Hold)',
  PRIMARY KEY (`id`),
  KEY `userhistories2_issueid_IDX` (`issuecve`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE IF NOT EXISTS `user_histories3` (
  `id` int NOT NULL AUTO_INCREMENT,
  `issuecve` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave de incidencia',
  `tipodefesarrollo` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Tipo de Desarrollo)',
  `uxdesignfigma` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (UX Design (figma))',
  `uxdesignfigmadate` datetime DEFAULT NULL COMMENT 'Campo personalizado (UX Design (figma) Date)',
  `userstorytype` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (User Story Type)',
  `featureconsideredqplanning` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Was the feature considered in the Q planning session?)',
  `dateoffirstresponse` datetime DEFAULT NULL COMMENT 'Campo personalizado ([CHART] Date of First Response)',
  `timeinStatus` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado ([CHART] Time in Status)',
  `firsttimedefect` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿A partir de cuándo se detectó por primera vez el defecto?)',
  `componentintegration` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Al realizar un análisis técnico, en que momento ocurrió la integración de componentes?)',
  `userimpact` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Cuál es el impacto de este defecto en el usuario final?)',
  `vobouser` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Durante el refinamiento de la Matriz de pruebas quienes dieron el Vo.Bo.?)',
  `porequirments` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿El Product Owner proporcionó requisitos claros y detallados para esta funcionalidad?)',
  `insidetestingstrategy` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿El defecto escapado estaba dentro de la matriz de cobertura de pruebas actual?)',
  `insidetechnicalrequirement` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿El defecto se relaciona con un requisito técnico (ambiguo) y fue omitido en los criterios de aceptación?)',
  `developwiththecnicalsolution` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿El desarrollo fue basado en la Technnical Solution?)',
  `testinginsideenviroment` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿El equipo de QA tuvo acceso a datos o a un entorno de pruebas que replicara adecuadamente las condiciones bajo las cuales ocurrió el defecto?)',
  `understanddevelopers` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿El equipo de desarrollo comprendió claramente los requisitos y las expectativas del negocio?)',
  `documentationdevelopers` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿El equipo de desarrollo documentó adecuadamente los cambios de componentes o validó la no afectación?)',
  `persistentorcontinueerror` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Es este un defecto recurrente, o ha ocurrido en versiones anteriores del producto?)',
  `productiondetected` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Este defecto fue identificado en producción?)',
  `timeorresourcesrestriction` json DEFAULT NULL COMMENT 'Campo personalizado (¿Existieron restricciones de tiempo o recursos (ej., requisitos, documentación) que pudieron haber afectado la calidad de las pruebas?)',
  `scopechanged` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Hubo algún cambio en el alcance de los requisitos?)',
  `testingstrategyrefined` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿La matriz de pruebas tuvo un refinamiento previo al Planning?)',
  `dependencysolved` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿La tarjeta está relacionada con el trabajo de otro equipo o tiene alguna dependencia (ej., nuevas funcionalidades con cambios en FE y BE)?)',
  `testingdatafailed` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Los casos de prueba fallaron debido a condiciones del entorno o de datos?)',
  `testingdataspecifics` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿No se ejecutaron casos de prueba específicos para esta área?)',
  `testingtypeexecuted` json DEFAULT NULL COMMENT 'Campo personalizado (¿Que tipo de pruebas asociados a este defecto fueron ejecutadas?)',
  `functionalitychanged` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Qué cambio reciente o funcionalidad de código podría haber causado el defecto?)',
  `allenviromentswasconsidered` json DEFAULT NULL COMMENT 'Campo personalizado (¿Se consideraron todos los canales y/o plataformas donde se considera esta funcionalidad?)',
  `testdatafordefect` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se crearon casos de prueba para este defecto?)',
  `externalpodcompliance` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se cumplió con los estándares de calidad sobre esta dependencia en el POD externo?)',
  `detectedduringcvt` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se identificó el defecto durante las pruebas de CVT?)',
  `detectednotscaled` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se identificó el defecto durante las pruebas pero no se escaló adecuadamente?)',
  `alltestexecuted` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se realizaron pruebas de regresión, integración o E2E? Si es así, ¿por qué no fue detectado el defecto?)',
  `codereviewexecuted` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se realizaron revisiones de código o revisiones entre pares?)',
  `tiskanalized` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se realizó un análisis de riesgo a nivel técnico?)',
  `acceptancecriteriascleared` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se revisó que las historias de usuario contienen los criterios de aceptación de forma clara?)',
  `acceptancecriteriaspocleared` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (¿Se validaron todos los criterios de aceptación definidos por el Product Owner?)',
  `comentario` json DEFAULT NULL COMMENT 'Comentario',
  `categoríadeestado` varchar(100) DEFAULT NULL COMMENT 'Categoría de estado',
  `categoríadeestadocambiada` datetime DEFAULT NULL COMMENT 'Categoría de estado cambiada',
  `principal` varchar(100) DEFAULT NULL COMMENT 'Principal',
  `parentsummary` varchar(100) DEFAULT NULL COMMENT 'Parent summary',
  PRIMARY KEY (`id`),
  KEY `userhistories3_issueId_IDX` (`issueCve`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
