CREATE TABLE IF NOT EXISTS `user_histories` (
  `id` int NOT NULL,
  `resumen` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Resumen',
  `issueId` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave de incidencia',
  `issueType` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Tipo de Incidencia',
  `state` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Estado',
  `projectId` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave del proyecto',
  `nombredelproyecto` varchar(100) DEFAULT NULL COMMENT 'Nombre del proyecto',
  `priority` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Prioridad',
  `assignPerson` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Persona asignada',
  `informador` varchar(100) DEFAULT NULL COMMENT 'Informador',
  `createPerson` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Creador',
  `createdDate` datetime NOT NULL COMMENT 'Creada',
  `lastModified` datetime NOT NULL COMMENT 'Actualizada',
  `lastview` datetime NOT NULL COMMENT 'Vista por Última Vez',
  `finalizeddate` datetime DEFAULT NULL COMMENT 'Resuelta',
  `fixedversion` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Versiones corregidas',
  `component` json DEFAULT NULL COMMENT 'Componentes',
  `expirationDate` datetime DEFAULT NULL COMMENT 'Fecha de vencimiento',
  `etiquetas` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Etiquetas',
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'Descripción',
  `envioroments` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Entorno',
  `interestedPersons` json DEFAULT NULL COMMENT 'Interesados',
  `issuelinkinternal` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Blocks)',
  `issuelinkoutgoing` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Blocks)',
  `issuelinkinternalcloner` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Cloners)',
  `issuelinkoutgoingcloner` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Cloners)',
  `issuelinkinternalissuesplit` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Issue split)',
  `issuelinkoutgoingissuesplit` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Issue split)',
  `issuelinkinternalproblem` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Problem/Incident)',
  `issuelinkoutgoingproblem` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Problem/Incident)',
  `issuelinkinternalrelates` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Relates)',
  `issuelinkoutgoingrelates` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Relates)',
  `attachments` json DEFAULT NULL COMMENT 'Adjunto',
  `dor` decimal(10,0) DEFAULT NULL COMMENT 'Campo personalizado (% DoR)',
  `ambiente` json DEFAULT NULL COMMENT 'Campo personalizado (Ambiente)',
  `assigneeqa` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Assignee QA)',
  `businessdata` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business Data)',
  `businessidea` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business Idea)',
  `po` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business PO)',
  `canal` json DEFAULT NULL COMMENT 'Campo personalizado (Canal)',
  `cardtype` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Card Type)',
  `carryover` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over)',
  `carryoverdetail` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Detail)',
  `carryoverdesviation` int DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Deviation)',
  `carryoverrecoverytime` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Recovery Time)',
  `causeoferrer` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Cause of error)',
  `codingstartdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Coding start date)',
  `complejidad` int DEFAULT NULL COMMENT 'Campo personalizado (Complejidad)',
  `componentsdor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Components)',
  `comprometida` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Comprometida)',
  `criteriaofacceptance` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Criteria of acceptance)',
  `definedenviroment` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Defined enviroment)',
  `desarrollointegradoparapruebasyliberación` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Desarrollo integrado para pruebas y liberación)',
  `domain` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Domain)',
  `epicLink` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Epic Link)',
  `epiclinkresumen` varchar(100) DEFAULT NULL COMMENT 'Epic Link Resumen',
  `errorexpectedbehavior` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Error - Expected Behavior)',
  `error Handling` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Error Handling)',
  `excepción` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Excepción)',
  `fechareadytoreview` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha Ready to review)',
  `fechacompromiso` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha compromiso)',
  `fechafinalización` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha finalización)',
  `fechaupdatecomprometida` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha update comprometida)',
  `flujo` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Flujo)',
  `functionalrequirements` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Functional Requirements)',
  `hoursindevreworks` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in Dev Reworks)',
  `hoursininprogress` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in In Progress)',
  `koursinonhold` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in on hold)',
  `iropstranstype` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (IROPs Trans Type)',
  `iniciativa` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Iniciativa)',
  `initiative` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Initiative)',
  `issuecolor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Issue color)',
  `j2Ctipoincidencia` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (J2C  Tipo Incidencia)',
  `journey` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Journey)',
  `kpi` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (KPI)',
  `latechanges` int DEFAULT NULL COMMENT 'Campo personalizado (Late Changes)',
  `leadtimeforchangeshrs` int DEFAULT NULL COMMENT 'Campo personalizado (Lead Time for Changes (Hrs))',
  `limitedScope` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Limited Scope)',
  `metrics` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Metrics)',
  `microservicescontract` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Microservices Contract)',
  `mitigateddependency` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Mitigated dependency)',
  `nodecasosdeprueba` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (No de casos de prueba)',
  `nonfunctionalrequirements` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Non Functional Requirements)',
  `onkoldreason` varchar(255) DEFAULT NULL COMMENT 'Campo personalizado (On Hold Reason)',
  `pod` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (POD)',
  `persistenterror` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Persistent Error)',
  `prioridadbacklog` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Prioridad Backlog)',
  `projectbenefitold` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Project Benefit - old)',
  `projectcostold` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Project Cost - old)',
  `pruebas` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Pruebas)',
  `qalead` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (QA Lead)',
  `quarter` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Quarter)',
  `ranked` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Rank)',
  `refinedcard` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Refined card)',
  `releasedeviation` int DEFAULT NULL COMMENT 'Campo personalizado (Release Deviation)',
  `releasedateactual` datetime DEFAULT NULL COMMENT 'Campo personalizado (Release date actual)',
  `releaseversion` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Release version)',
  `reportadopor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Reportado por)',
  `resolución` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Resolución)',
  `softwarefactorymember` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Software Factory Member)',
  `specialPNRGeneration` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Special PNR Generation)',
  `sprint` varchar(100) DEFAULT NULL COMMENT 'Sprint',
  `sprintActual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint Actual)',
  `sprintAppActual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Actual)',
  `sprintAppPlanned` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Planned)',
  `sprintEndDate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint End Date)',
  `sprintPlanned` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint Planned)',
  `sprintStartDate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint Start Date)',
  `startdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Start date)',
  `storyPointReestimation` datetime DEFAULT NULL COMMENT 'Campo personalizado (Story Point Reestimation)',
  `storyPoints` int DEFAULT NULL COMMENT 'Campo personalizado (Story Points)',
  `storyPointsQA` int DEFAULT NULL COMMENT 'Campo personalizado (Story Points QA)',
  `technicalLead` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Technical Lead)',
  `technicalSolution` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Technical Solution)',
  `technicalSolutionDetail` varchar(2048) DEFAULT NULL COMMENT 'Campo personalizado (Technical Solution Detail)',
  `testingStrategy` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Testing Strategy)',
  `timeinDevRework` datetime DEFAULT NULL COMMENT 'Campo personalizado (Time in Dev Rework)\r\nSe debe hacer la conversion de string a 00d 00h 00m 00s',
  `timeinInProgress` datetime DEFAULT NULL COMMENT 'Campo personalizado (Time in In Progress)\r\nSe debe hacer la conversion de string a 00d 00h 00m 00s',
  `timeinOnHold` datetime DEFAULT NULL COMMENT 'Campo personalizado (Time in On Hold)\r\nHay que hacer la conversion de String a 00d 00k 00m 00s',
  `tipodeDesarrollo` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Tipo de Desarrollo)',
  `uxDesignfigma` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (UX Design (figma))',
  `userStoryType` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (User Story Type)',
  `dateofFirstResponse` datetime DEFAULT NULL COMMENT 'Campo personalizado ([CHART] Date of First Response)',
  `timeinStatus` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado ([CHART] Time in Status)',
  `comentario` json DEFAULT NULL COMMENT 'Comentario',
  `categoríadeestado` varchar(100) DEFAULT NULL COMMENT 'Categoría de estado',
  `categoríadeestadocambiada` datetime DEFAULT NULL COMMENT 'Categoría de estado cambiada',
  `principal` varchar(100) DEFAULT NULL COMMENT 'Principal',
  `parentsummary` varchar(100) DEFAULT NULL COMMENT 'Parent summary',
  PRIMARY KEY (`id`),
  KEY `userhistories_issueId_IDX` (`issueId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;