CREATE TABLE `opensprint` (
  `id` int NOT NULL AUTO_INCREMENT,
  `issuecve` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave de incidencia',
  `state` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Estado',
  `priority` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Prioridad',
  `assignperson` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Persona asignada',
  `lastmodified` datetime DEFAULT NULL COMMENT 'Actualizada',
  `lastview` datetime DEFAULT NULL COMMENT 'Vista por Última Vez',
  `finalizeddate` datetime DEFAULT NULL COMMENT 'Resuelta',
  `expirationdate` datetime DEFAULT NULL COMMENT 'Fecha de vencimiento',
  `carryover` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over)',
  `carryoverdetail` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Detail)',
  `carryoverdesviation` int DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Deviation)',
  `carryoverrecoverytime` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Recovery Time)',
  `codequality` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Code_quality)',
  `fechafinalización` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha finalización)',
  `fechaupdatecomprometida` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha update comprometida)',
  `hoursindevreworks` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in Dev Reworks)',
  `hoursininprogress` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in In Progress)',
  `koursinonhold` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in on hold)',
  `kissrecoverytime` json DEFAULT NULL COMMENT 'Campo personalizado (KISS Recovery time)',
  `latechanges` int DEFAULT NULL COMMENT 'Campo personalizado (Late Changes)',
  `leadtime` int DEFAULT NULL COMMENT 'Campo personalizado (Lead Time)',
  `leadtimeforchangeshrs` int DEFAULT NULL COMMENT 'Campo personalizado (Lead Time for Changes (Hrs))',
  `sprint` json DEFAULT NULL COMMENT 'Sprint',
  `sprintactual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint Actual)',
  `sprintappactual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Actual)',
  `sprintappplanned` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Planned)',
  `sprintenddate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint End Date)',
  `sprintplanned` varchar(10) DEFAULT NULL COMMENT 'Campo personalizado (Sprint Planned)',
  `sprintstartdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint Start Date)',
  `startdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Start date)',
  `timeindevrework` varchar(20) DEFAULT NULL COMMENT 'Campo personalizado (Time in Dev Rework)',
  `timeininprogress` varchar(20) DEFAULT NULL COMMENT 'Campo personalizado (Time in In Progress)',
  `timeinonhold` varchar(20) DEFAULT NULL COMMENT 'Campo personalizado (Time in On Hold)',
  `pod` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `carryover_UNIQUE` (`carryover`),
  KEY `cierresprint1_issueid_IDX` (`issuecve`) USING BTREE,
  KEY `idx_sprintactualcierre` (`sprintactual`)
) ENGINE=InnoDB AUTO_INCREMENT=90 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;