CREATE SCHEMA IF NOT EXISTS statsfabric;

use statsfabric;

CREATE TABLE `statsfabric`.`userhistories` (
  `id` INT NOT NULL,
  `issueId` VARCHAR(45) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `IssueType` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `projectId` VARCHAR(45) NOT NULL,
  `priority` VARCHAR(45) NOT NULL,
  `assignPerson` VARCHAR(255) NULL,
  `createPerson` VARCHAR(255) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `lastModified` DATETIME NOT NULL,
  `lastview` DATETIME NOT NULL,
  `finalizeddate` DATETIME NULL,
  `fixedversion` VARCHAR(45) NULL,
  `component` VARCHAR(45) NULL,
  `components` VARCHAR(255) NULL,
  `expirationDate` DATETIME NULL,
  `Etiquetas` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `envioroments` VARCHAR(255) NULL,
  `interestedPersons` JSON NULL,
  `issuelinkinternal` JSON NULL,
  `issuelinkoutgoing` JSON NULL,
  `issuelinkinternalcloner` JSON NULL,
  `issuelinkoutgoingcloner` VARCHAR(45) NULL,
  `issuelinkinternalissuesplit` VARCHAR(45) NULL,
  `issuelinkoutgoingissuesplit` VARCHAR(45) NULL,
  `issuelinkinternalproblem` VARCHAR(45) NULL,
  `issuelinkoutgoingproblem` VARCHAR(45) NULL,
  `issuelinkinternalrelates` JSON NULL,
  `issuelinkoutgoingrelates` JSON NULL,
  `attachments` JSON NULL,
  `DOR` DECIMAL NULL,
  `envioroentpersonilized` JSON NULL,
  `assigneeqa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));
