CREATE SCHEMA IF NOT EXISTS aeromexico;

use aeromexico;

CREATE TABLE `userhistories` (
  `id` int NOT NULL,
  `Resumen` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Resumen',
  `issueId` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave de incidencia',
  `IssueType` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Tipo de Incidencia',
  `state` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Estado',
  `projectId` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Clave del proyecto',
  `Nombredelproyecto` varchar(100) DEFAULT NULL COMMENT 'Nombre del proyecto',
  `priority` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Prioridad',
  `assignPerson` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Persona asignada',
  `Informador` varchar(100) DEFAULT NULL COMMENT 'Informador',
  `createPerson` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Creador',
  `createdDate` datetime NOT NULL COMMENT 'Creada',
  `lastModified` datetime NOT NULL COMMENT 'Actualizada',
  `lastview` datetime NOT NULL COMMENT 'Vista por Última Vez',
  `finalizeddate` datetime DEFAULT NULL COMMENT 'Resuelta',
  `fixedversion` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Versiones corregidas',
  `component` json DEFAULT NULL COMMENT 'Componentes',
  `expirationDate` datetime DEFAULT NULL COMMENT 'Fecha de vencimiento',
  `Etiquetas` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Etiquetas',
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'Descripción',
  `envioroments` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Entorno',
  `interestedPersons` json DEFAULT NULL COMMENT 'Interesados',
  `issuelinkinternal` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Blocks)',
  `issuelinkoutgoing` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Blocks)',
  `issuelinkinternalcloner` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Cloners)',
  `issuelinkoutgoingcloner` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Cloners)',
  `issuelinkinternalissuesplit` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Issue split)',
  `issuelinkoutgoingissuesplit` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Issue split)',
  `issuelinkinternalproblem` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Problem/Incident)',
  `issuelinkoutgoingproblem` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Problem/Incident)',
  `issuelinkinternalrelates` json DEFAULT NULL COMMENT 'Enlace a la incidencia interna (Relates)',
  `issuelinkoutgoingrelates` json DEFAULT NULL COMMENT 'Enlace de incidencia saliente (Relates)',
  `attachments` json DEFAULT NULL COMMENT 'Adjunto',
  `DOR` decimal(10,0) DEFAULT NULL COMMENT 'Campo personalizado (% DoR)',
  `ambiente` json DEFAULT NULL COMMENT 'Campo personalizado (Ambiente)',
  `assigneeqa` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Assignee QA)',
  `businessdata` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business Data)',
  `businessidea` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business Idea)',
  `PO` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Business PO)',
  `canal` json DEFAULT NULL COMMENT 'Campo personalizado (Canal)',
  `cardtype` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Card Type)',
  `carryover` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over)',
  `carryoverdetail` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Detail)',
  `carryoverdesviation` int DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Deviation)',
  `carryoverrecoverytime` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Carry Over Recovery Time)',
  `causeoferrer` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Cause of error)',
  `codingstartdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Coding start date)',
  `complejidad` int DEFAULT NULL COMMENT 'Campo personalizado (Complejidad)',
  `componentsdor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Components)',
  `comprometida` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Comprometida)',
  `criteriaofacceptance` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Criteria of acceptance)',
  `definedenviroment` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Defined enviroment)',
  `desarrollointegradoparapruebasyliberación` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Desarrollo integrado para pruebas y liberación)',
  `Domain` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Domain)',
  `epicLink` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Epic Link)',
  `epiclinkresumen` varchar(100) DEFAULT NULL COMMENT 'Epic Link Resumen',
  `errorexpectedbehavior` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Error - Expected Behavior)',
  `Error Handling` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Error Handling)',
  `Excepción` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Excepción)',
  `fechareadytoreview` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha Ready to review)',
  `fechacompromiso` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha compromiso)',
  `fechafinalización` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha finalización)',
  `fechaupdatecomprometida` datetime DEFAULT NULL COMMENT 'Campo personalizado (Fecha update comprometida)',
  `flujo` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Flujo)',
  `functionalrequirements` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Functional Requirements)',
  `hoursindevreworks` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in Dev Reworks)',
  `hoursininprogress` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in In Progress)',
  `koursinonhold` int DEFAULT NULL COMMENT 'Campo personalizado (Hours in on hold)',
  `IROPstranstype` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (IROPs Trans Type)',
  `iniciativa` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Iniciativa)',
  `initiative` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Initiative)',
  `issuecolor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Issue color)',
  `J2Ctipoincidencia` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (J2C  Tipo Incidencia)',
  `Journey` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Journey)',
  `KPI` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (KPI)',
  `Latechanges` int DEFAULT NULL COMMENT 'Campo personalizado (Late Changes)',
  `Leadtimeforchangeshrs` int DEFAULT NULL COMMENT 'Campo personalizado (Lead Time for Changes (Hrs))',
  `LimitedScope` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Campo personalizado (Limited Scope)',
  `Metrics` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Metrics)',
  `Microservicescontract` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Microservices Contract)',
  `Mitigateddependency` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Mitigated dependency)',
  `Nodecasosdeprueba` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (No de casos de prueba)',
  `Nonfunctionalrequirements` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Non Functional Requirements)',
  `Onkoldreason` varchar(255) DEFAULT NULL COMMENT 'Campo personalizado (On Hold Reason)',
  `POD` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (POD)',
  `Persistenterror` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Persistent Error)',
  `Prioridadbacklog` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Prioridad Backlog)',
  `Projectbenefitold` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Project Benefit - old)',
  `Projectcostold` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Project Cost - old)',
  `Pruebas` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Pruebas)',
  `QAlead` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (QA Lead)',
  `Quarter` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Quarter)',
  `rank` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Rank)',
  `Refinedcard` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Refined card)',
  `Releasedeviation` int DEFAULT NULL COMMENT 'Campo personalizado (Release Deviation)',
  `Releasedateactual` datetime DEFAULT NULL COMMENT 'Campo personalizado (Release date actual)',
  `Releaseversion` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Release version)',
  `Reportadopor` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Reportado por)',
  `Resolución` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Resolución)',
  `Softwarefactorymember` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Software Factory Member)',
  `SpecialPNRGeneration` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Special PNR Generation)',
  `Sprint` varchar(100) DEFAULT NULL COMMENT 'Sprint',
  `SprintActual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint Actual)',
  `SprintAppActual` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Actual)',
  `SprintAppPlanned` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Sprint App Planned)',
  `SprintEndDate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint End Date)',
  `SprintPlanned` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint Planned)',
  `SprintStartDate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Sprint Start Date)',
  `Startdate` datetime DEFAULT NULL COMMENT 'Campo personalizado (Start date)',
  `StoryPointReestimation` datetime DEFAULT NULL COMMENT 'Campo personalizado (Story Point Reestimation)',
  `StoryPoints` int DEFAULT NULL COMMENT 'Campo personalizado (Story Points)',
  `StoryPointsQA` int DEFAULT NULL COMMENT 'Campo personalizado (Story Points QA)',
  `TechnicalLead` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Technical Lead)',
  `TechnicalSolution` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Technical Solution)',
  `TechnicalSolutionDetail` varchar(2048) DEFAULT NULL COMMENT 'Campo personalizado (Technical Solution Detail)',
  `TestingStrategy` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Testing Strategy)',
  `TimeinDevRework` datetime DEFAULT NULL COMMENT 'Campo personalizado (Time in Dev Rework)\r\nSe debe hacer la conversion de string a 00d 00h 00m 00s',
  `TimeinInProgress` datetime DEFAULT NULL COMMENT 'Campo personalizado (Time in In Progress)\r\nSe debe hacer la conversion de string a 00d 00h 00m 00s',
  `TimeinOnHold` datetime DEFAULT NULL COMMENT 'Campo personalizado (Time in On Hold)\r\nHay que hacer la conversion de String a 00d 00k 00m 00s',
  `TipodeDesarrollo` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (Tipo de Desarrollo)',
  `UXDesignfigma` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (UX Design (figma))',
  `UserStoryType` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado (User Story Type)',
  `DateofFirstResponse` datetime DEFAULT NULL COMMENT 'Campo personalizado ([CHART] Date of First Response)',
  `TimeinStatus` varchar(100) DEFAULT NULL COMMENT 'Campo personalizado ([CHART] Time in Status)',
  `Comentario` json DEFAULT NULL COMMENT 'Comentario',
  `Categoríadeestado` varchar(100) DEFAULT NULL COMMENT 'Categoría de estado',
  `Categoríadeestadocambiada` datetime DEFAULT NULL COMMENT 'Categoría de estado cambiada',
  `Principal` varchar(100) DEFAULT NULL COMMENT 'Principal',
  `Parentsummary` varchar(100) DEFAULT NULL COMMENT 'Parent summary',
  PRIMARY KEY (`id`),
  KEY `userhistories_issueId_IDX` (`issueId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;